# Q1：交錯區塊反轉與取值

### 已知一個 `numpy` 二維陣列 `A`，形狀為 `(8, 8)`，內容為 0~63：

請只使用 indexing 與 slicing（不可使用 for / while / reshape / flatten)完成下列操作：
1. 將 `A` 切成 **4 個 4×4 子區塊**
2. 對 **右下角子區塊** 進行：
   * 列順序反轉
   * 欄順序反轉
3. 請在8×8的陣列中顯示出`偶數的數字`其他都會零

In [18]:
import numpy as np
# ----------- your code -----------
A = np.arange(64).reshape(8,8)
print(A, '\n')

sub = A[4:, 4:] #逗號前面是row 後面是colume
print(sub, '\n')

rvs = A[:-5:-1, 4:]
print(rvs, '\n')

A_W = np.where(A%2==0, A, 0)
print(A_W)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] 

[[36 37 38 39]
 [44 45 46 47]
 [52 53 54 55]
 [60 61 62 63]] 

[[60 61 62 63]
 [52 53 54 55]
 [44 45 46 47]
 [36 37 38 39]] 

[[ 0  0  2  0  4  0  6  0]
 [ 8  0 10  0 12  0 14  0]
 [16  0 18  0 20  0 22  0]
 [24  0 26  0 28  0 30  0]
 [32  0 34  0 36  0 38  0]
 [40  0 42  0 44  0 46  0]
 [48  0 50  0 52  0 54  0]
 [56  0 58  0 60  0 62  0]]


---
# Q2 請建立一個 $8 \times 8$ 的全 0 矩陣，並完成以下操作：

1. 將矩陣的最外層（邊框）全部填入 $1$。
2. 將矩陣最中間的 $2 \times 2$ 區域填入 $9$。
3. 使用切片（Slicing）提取出扣除最外層邊框後的「內核」部分（即 $6 \times 6$ 的矩陣）。

In [14]:
import numpy as np

# 建立 8x8 全 0 矩陣
# ----------- your code -----------
B = np.zeros([8,8], dtype = int)
print(B)
B[0, : ] = B[ : ,0] = B[ : ,7] =B[7, : ] =1
print(B)
B[3:5 , 3:5] = 9
print(B)
B_slice = B[1:7, 1:7]
print(B_slice)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 9 9 0 0 1]
 [1 0 0 9 9 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 9 9 0 0]
 [0 0 9 9 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


---
# Q3：標準化後的非線性轉換與統計量

給定一個一維 NumPy 陣列：

x = np.array([4, 9, 16, 25, 36], dtype=float)

請完成以下步驟 (列印出來的結果都以小數點3位四捨五入為主：
1. 對 `x` 取平方根
2. 對結果進行 **標準化**（z-score）
   $$z = \frac{x - x_{mean}}{x_{std}}$$
3. 對標準化後的結果計算：
   * 絕對值
4. 輸出最後結果的 **平均值**

In [25]:
import numpy as np

# ----------- your code -----------
x = np.array([4, 9, 16, 25, 36], dtype=float)
case1 = np.sqrt(x)
print(case1)
z = (x - np.mean(x))/np.std(x)
print(np.round(z,3))
case3 = np.abs(z)
print(np.round(case3,3))
case4 = np.mean(case3)
print(np.round(case4,3))


[2. 3. 4. 5. 6.]
[-1.224 -0.787 -0.175  0.612  1.574]
[1.224 0.787 0.175 0.612 1.574]
0.874


---
# Q4. 給定一個二維陣列：

```python
X = np.array([[1,  2,  3],
              [4,  5,  6],
              [7,  8,  9]], dtype=float)
```

請完成以下步驟：

1. 對 `X` **沿著欄（axis=0）** 計算累積和
2. 對累積和結果取 **平方根**
3. 再對結果 **沿著列（axis=1）** 計算平均值
4. 輸出一維陣列 `result`

In [2]:
import numpy as np

# ----------- your code -----------
y = np.array([[1,  2,  3],
              [4,  5,  6],
              [7,  8,  9]], dtype=float)
case1 = y.cumsum(0)
print(case1)
case2 = np.sqrt(case1)
print(case2)
case3 = case2.mean(1)
print(case3)

[[ 1.  2.  3.]
 [ 5.  7.  9.]
 [12. 15. 18.]]
[[1.         1.41421356 1.73205081]
 [2.23606798 2.64575131 3.        ]
 [3.46410162 3.87298335 4.24264069]]
[1.38208812 2.6272731  3.85990855]


---
# Q5. 假設有一間商店有四種會員等級：`Gold`, `Silver`, `Bronze`, `Regular`。

1. 請使用 NumPy 隨機產生 **1000 次** 抽樣結果，抽樣機率分配如下：
* `Gold`: 5%
* `Silver`: 15%
* `Bronze`: 30%
* `Regular`: 50%

2. 統計這 1000 次抽樣中，每種等級分別出現了幾次？
3. **加分：** 將結果存入一個字典（Dictionary）。

In [9]:
import numpy as np

# 定義選項與權重
levels = ['Gold', 'Silver', 'Bronze', 'Regular']
weights = [0.05, 0.15, 0.30, 0.50]

# ----------- your code -----------
case1 = np.random.choice(levels, p = weights, size = 1000)
print(case1)
case2 = np.unique(case1, return_counts = True)
print(case2)
case3 = dict(zip(case1, case2))
print(case3)


['Bronze' 'Regular' 'Bronze' 'Regular' 'Gold' 'Regular' 'Bronze' 'Bronze'
 'Regular' 'Regular' 'Bronze' 'Regular' 'Regular' 'Regular' 'Regular'
 'Silver' 'Bronze' 'Regular' 'Regular' 'Bronze' 'Regular' 'Regular'
 'Regular' 'Regular' 'Regular' 'Regular' 'Regular' 'Regular' 'Bronze'
 'Regular' 'Gold' 'Bronze' 'Regular' 'Regular' 'Regular' 'Gold' 'Regular'
 'Silver' 'Regular' 'Silver' 'Regular' 'Gold' 'Silver' 'Regular' 'Regular'
 'Regular' 'Bronze' 'Regular' 'Bronze' 'Regular' 'Regular' 'Regular'
 'Silver' 'Gold' 'Bronze' 'Bronze' 'Regular' 'Regular' 'Regular' 'Bronze'
 'Regular' 'Regular' 'Regular' 'Bronze' 'Regular' 'Bronze' 'Bronze'
 'Regular' 'Regular' 'Regular' 'Bronze' 'Bronze' 'Silver' 'Bronze' 'Gold'
 'Bronze' 'Bronze' 'Bronze' 'Silver' 'Bronze' 'Regular' 'Bronze' 'Regular'
 'Regular' 'Regular' 'Regular' 'Bronze' 'Regular' 'Silver' 'Regular'
 'Bronze' 'Gold' 'Regular' 'Regular' 'Regular' 'Bronze' 'Silver' 'Regular'
 'Regular' 'Regular' 'Regular' 'Regular' 'Regular' 'Bronze' 'Regu